### ISSUE TITLE
parse_schema_descriptor is not defined

### ISSUE THREAD

**Issue by marcosschroh** [rwhitten577/faust-example#1]
Hi,

how are you? I have the following exception: `NameError: name 'parse_schema_descriptor' is not defined`. In `app.py` is never imported, where this function comes from?

**Comment by rwhitten577** [comment]
Hi there, sorry for the delay on this. Haven't checked in in a while. 

This project is abstracted from a private repo and that function references an internal library. I have just updated the master branch to replace the end result - passing the Faust avro serializer a parsed JSON avro schema using avro.schema.Parse(json_string).
